# Generated by Django 6.1.1 on 2026-10-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
